pipeline {
    agent any

    stages {

        stage('Build Backend Image') {
            steps {
                sh '''
                docker build -t backend-app CC_LAB-6/backend
                '''
            }
        }

        stage('Run Backends') {
            steps {
                sh '''
                docker rm -f backend1 backend2 || true
                docker run -d --name backend1 backend-app
                docker run -d --name backend2 backend-app
                '''
            }
        }

        stage('Run NGINX Load Balancer') {
            steps {
                sh '''
                docker rm -f nginx-lb || true
                docker build -t nginx-lb CC_LAB-6/nginx
                docker run -d -p 80:80 --name nginx-lb nginx-lb
                '''
            }
        }
    }
}
